name: GitHub Readme Stats

on:
  schedule:
    - cron: '0 */12 * * *'
  workflow_dispatch: 

jobs:
  update-stats:
    runs-on: ubuntu-latest
    permissions:
      contents: write
    steps:
      - name: Checkout Repository
        uses: actions/checkout@v4

      - name: Generate general stats card
        uses: stats-organization/github-readme-stats-action@v2
        with:
          card: stats
          options: 'username=Onyx-i7&theme=radical&show_icons=true&count_private=true'
          token: ${{ secrets.GH_TOKEN }}
          path: ./generated-stats/github-readme-stats.svg

      - name: Generate top languages card
        uses: stats-organization/github-readme-stats-action@v2
        with:
          card: top-langs
          options: 'username=Onyx-i7&theme=radical&show_icons=true&locale=en&layout=compact'
          token: ${{ secrets.GH_TOKEN }}
          path: ./generated-stats/github-top-langs.svg

      - name: Commit & Push Changes
        run: |
          git config --global user.name "github-actions[bot]"
          git config --global user.email "41898282+github-actions[bot]@users.noreply.github.com"
          git add .
          git diff-index --quiet HEAD || git commit -m "Update GitHub Readme Stats"
          git push
