name: GitHub Readme Stats

on:
  schedule:
    - cron: '0 */12 * * *'
  workflow_dispatch: 

jobs:
  update-stats:
    runs-on: ubuntu-latest
    permissions:
      contents: write
    steps:
      - name: Checkout Repository
        uses: actions/checkout@v4

      # Crear la carpeta por si acaso no existe
      - name: Create generated-stats directory
        run: mkdir -p ./generated-stats

      # 1. Generar la tarjeta de estadísticas generales
      - name: Generate general stats card
        uses: stats-organization/github-readme-stats-action@v2
        with:
          card: stats
          options: 'username=Onyx-i7&theme=radical&show_icons=true&count_private=true'
          token: ${{ secrets.GH_TOKEN }}
          path: ./generated-stats/github-readme-stats.svg

      # 2. Generar la tarjeta de lenguajes más usados
      - name: Generate top languages card
        uses: stats-organization/github-readme-stats-action@v2
        with:
          card: top-langs
          options: 'username=Onyx-i7&theme=radical&show_icons=true&locale=en&layout=compact'
          token: ${{ secrets.GH_TOKEN }}
          path: ./generated-stats/github-top-langs.svg

      # 3. Descargar Racha
      - name: Download Streak Stats
        run: |
          curl -s "https://github-readme-streak-stats.herokuapp.com/?user=Onyx-i7&theme=radical&hide_border=true" -o ./generated-stats/github-streak-stats.svg

      # 4. Guardar todos los cambios
      - name: Commit & Push Changes
        run: |
          git config --global user.name "github-actions[bot]"
          git config --global user.email "41898282+github-actions[bot]@users.noreply.github.com"
          git add .
          git diff-index --quiet HEAD || git commit -m "Update GitHub Readme Stats and Streak"
          git push
